sudo: false
language: python
python:
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py test
  - coverage run manage.py test

after_success: coveralls

after_success:
  - coveralls
