language: python
python:
  - "3.5"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - python manage.py test
  - coverage run manage.py test

after_success: coveralls
