language: python

python:
  - 2.7
  - 3.5

before_install:
  - export DJANGO_SETTINGS_MODULE=sitp_scraper.settings
  - python manage.py syncdb –migrate –noinput

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
