language: python
python:
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE="sitp_scraper.settings"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors

script:
  - python manage.py test
  - coverage run manage.py test

after_success: coveralls
