# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Telegram')])),
                ('chat_user_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('timezone', models.SmallIntegerField(null=True)),
                ('locale', models.CharField(default='', max_length=10)),
                ('requests_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotUserRequestStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_count', models.BigIntegerField(default=0)),
                ('day', models.DateField()),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitp_bot.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Telegram')])),
                ('phrase', models.CharField(max_length=500)),
                ('requests_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messagestats',
            unique_together=set([('source', 'phrase')]),
        ),
        migrations.AlterUniqueTogether(
            name='botuser',
            unique_together=set([('source', 'chat_user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='botuserrequeststats',
            unique_together=set([('bot_user', 'day')]),
        ),
    ]
