# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('link', models.URLField(default='')),
                ('address', models.CharField(max_length=255)),
                ('sublocality', models.CharField(default='', max_length=150)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('route_type', models.PositiveSmallIntegerField(choices=[(6, 'Troncal Sistema TransMilenio'), (7, 'Alimentadora'), (8, 'Urbana'), (9, 'Complementaria'), (10, 'Especial')])),
                ('map_link', models.URLField(default='')),
                ('schedule', models.CharField(max_length=500)),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Ida'), (2, 'Vuelta')])),
                ('position', models.PositiveIntegerField()),
                ('bus_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitp_scraper.BusStation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='sitp_scraper.Route')),
            ],
        ),
    ]
