# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitp_scraper', '0002_auto_20160910_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstation',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='routestations',
            options={'ordering': ['direction', 'position']},
        ),
        migrations.AddField(
            model_name='busstation',
            name='related_stations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_busstation_related_stations_+', to='sitp_scraper.BusStation'),
        ),
        migrations.AlterField(
            model_name='routestations',
            name='bus_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='sitp_scraper.BusStation'),
        ),
    ]
