# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitp_scraper', '0003_auto_20161016_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='busstation',
            name='related_stations',
            field=models.ManyToManyField(blank=True, related_name='_busstation_related_stations_+', to='sitp_scraper.BusStation'),
        ),
        migrations.AlterField(
            model_name='busstation',
            name='sublocality',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
