# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitp_scraper', '0004_auto_20161017_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='location_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Correcto'), (2, 'Por validar'), (3, 'Incorrecto')], default=2),
        ),
    ]
