# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 21:23
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.gis.geos import Point


def update_location(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    BusStation = apps.get_model("sitp_scraper", "BusStation")
    for bus_station in BusStation.objects.all():
        bus_station.location = Point(bus_station.longitude, bus_station.latitude)
        bus_station.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sitp_scraper', '0006_busstation_location'),
    ]

    operations = [
        migrations.RunPython(update_location),
    ]
